app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('project', 'ProjectController');
Route::resource('project.module', 'ModuleController');
Route::get('project/{project}/module/{module}/submodule/create', [
    'as' => 'project.module.submodule.create', 'uses' => 'ModuleController@submodule'
]);
Route::resource('project.module.page', 'PageController');
Route::resource('project.module.page.image', 'ImageController');
Route::resource('project.module.page.image.proposal', 'ProposalController');

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'authors',
        'planned_modules',
        'planned_pages',
        'format',
        'alternative_format',
        'complementary_materials',
        'notes',
        'isbn',
    ];

    /**
     * Get all of the modules for the project.
     */
    public function modules()
    {
        return $this->hasMany(Module::class);
    }

    /**
     * Get only the root modules for the project.
     */
    public function rootModules()
    {
        return $this->modules()->whereNull('parent_module');
    }
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProjectRequest;
use App\Project;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $projects = Project::all();
        return view('project.index', compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $project = new Project();
        return view('project.create', compact('project'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  ProjectRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProjectRequest $request)
    {
        $project = new Project( $request->all() );
        $project->save();
        return redirect()->route('project.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  Project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        return view('project.show', compact('project'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        return view('project.edit', compact('project'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  ProjectRequest  $request
     * @param  Project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(ProjectRequest $request, Project $project)
    {
        $project->update( $request->all() );
        $project->save();
        return redirect()->route('project.show', [$project]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        $project->delete();
        return redirect()->route('project.index');
    }
}

resources/views/project/_form.blade.php
<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
    {!! Form::label('name', 'Name', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::text('name', $project->name, ['class' => 'form-control', 'placeholder' => 'Project Name']) !!}
        {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('isbn') ? 'has-error' : '' }}">
    {!! Form::label('isbn', 'ISBN', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::text('isbn', $project->isbn, ['class' => 'form-control', 'placeholder' => 'ISBN']) !!}
        {!! $errors->first('isbn', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('planned_modules') ? 'has-error' : '' }}">
    {!! Form::label('planned_modules', 'Planned modules', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::text('planned_modules', $project->planned_modules, ['class' => 'form-control', 'placeholder' => 'Planned modules']) !!}
        {!! $errors->first('planned_modules', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('planned_pages') ? 'has-error' : '' }}">
    {!! Form::label('planned_pages', 'Planned pages', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::text('planned_pages', $project->planned_pages, ['class' => 'form-control', 'placeholder' => 'Planned pages']) !!}
        {!! $errors->first('planned_pages', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('authors') ? 'has-error' : '' }}">
    {!! Form::label('authors', 'Authors', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::textarea('authors', $project->authors, ['class' => 'form-control', 'placeholder' => 'Authors']) !!}
        {!! $errors->first('authors', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('format') ? 'has-error' : '' }}">
    {!! Form::label('format', 'Format', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::textarea('format', $project->format, ['class' => 'form-control', 'placeholder' => 'Format']) !!}
        {!! $errors->first('format', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('alternative_format') ? 'has-error' : '' }}">
    {!! Form::label('alternative_format', 'Alternative format', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::textarea('alternative_format', $project->alternative_format, ['class' => 'form-control', 'placeholder' => 'Alternative format']) !!}
        {!! $errors->first('alternative_format', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('complementary_materials') ? 'has-error' : '' }}">
    {!! Form::label('complementary_materials', 'Complementary materials', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::textarea('complementary_materials', $project->complementary_materials, ['class' => 'form-control', 'placeholder' => 'Complementary materials']) !!}
        {!! $errors->first('complementary_materials', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group {{ $errors->has('notes') ? 'has-error' : '' }}">
    {!! Form::label('notes', 'Notes', ['class' => 'col-sm-2 control-label']) !!}
    <div class="col-sm-10">
        {!! Form::textarea('notes', $project->notes, ['class' => 'form-control', 'placeholder' => 'Notes']) !!}
        {!! $errors->first('notes', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        {!! Form::submit('Save', ['class' => 'btn btn-success pull-right']) !!}
    </div>
</div>

resources/views/project/_submodules.blade.php
<tr>
    <td>{!! link_to_route('project.module.show', str_repeat('+', $count) . ' ' . $module->name, [$project, $module], ['class' => '']) !!}</td>
    <td>{{ $module->pages()->count() }}</td>
    <td>{{ $module->planned_pages }}</td>
    <td>{!! link_to_route('project.module.edit', 'Edit', [$project, $module], ['class' => 'btn btn-xs btn-primary']) !!}</td>
    <td>{!! link_to_route('project.module.submodule.create', 'New Submodule', [$project, $module], ['class' => 'btn btn-xs btn-success']) !!}</td>
    <td>
        {!! Form::open(['route' => ['project.module.destroy', $project, $module], 'method' => 'delete']) !!}
        {!! Form::submit('Delete', ['class' => 'btn btn-xs btn-danger']) !!}
        {!! Form::close() !!}
    </td>
</tr>
@foreach($module->submodules as $submodule)
    @include('project._submodules', ['module' => $submodule, 'count' => $count+1])
@endforeach

resources/views/project/create.blade.php
@extends('app')

@section('content')

    <div class="row">

        <div class="col-md-12">

            <h1>Create Project</h1>

            {!! Form::model($project, ['route' => ['project.store'], 'class' => 'form-horizontal']) !!}

                @include('project._form')

            {!! Form::close() !!}

        </div>

    </div>

@endsection

resources/views/project/edit.blade.php
@extends('app')

@section('content')

    <div class="row">

        <div class="col-md-12">

            <h1>Edit Project</h1>

            {!! Form::model($project, ['route' => ['project.update', $project], 'method' => 'put', 'class' => 'form-horizontal']) !!}

                @include('project._form')

            {!! Form::close() !!}

        </div>

    </div>

@endsection

resources/views/project/index.blade.php
@extends('app')

@section('content')

    <div class="row">

        <div class="col-md-12">
            <h1>
                Projects
                <small class="pull-right">
                    {!! link_to_route('project.create', 'New', [], ['class' => 'btn btn-success']) !!}
                </small>
            </h1>
        </div>
        <div class="col-md-12">

            <table class="table table-condensed">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>ISBN</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach($projects as $project)
                <tr>
                    <td>{!! link_to_route('project.show', $project->name, [$project], ['class' => '']) !!}</td>
                    <td>{{ $project->isbn }}</td>
                    <td class="shrink">{!! link_to_route('project.edit', 'Edit', [$project], ['class' => 'btn btn-xs btn-primary']) !!}</td>
                    <td class="shrink">
                        {!! Form::open(['route' => ['project.destroy', $project->id], 'method' => 'delete']) !!}
                            {!! Form::submit('Delete', ['class' => 'btn btn-xs btn-danger']) !!}
                        {!! Form::close() !!}
                    </td>
                </tr>
                @endforeach
                </tbody>
            </table>

        </div>

    </div>

@endsection

resources/views/project/show.blade.php
@extends('app')

@section('content')

    @include('partials.breadcrumbs')

    <div class="row">
        <div class="col-md-12">
            <h1>{{ $project->name }}</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <p><strong>ISBN:</strong> {{ $project->isbn }}</p>
        </div>
        <div class="col-md-4">
            <p><strong>Planned modules:</strong> {{ $project->planned_modules }}</p>
        </div>
        <div class="col-md-4">
            <p><strong>Planned pages:</strong> {{ $project->planned_pages }}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <p><strong>Authors:</strong> {{ $project->authors }}</p>
        </div>
        <div class="col-md-6">
            <p><strong>Format:</strong> {{ $project->format }}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <p><strong>Alternative format:</strong> {{ $project->alternative_format }}</p>
        </div>
        <div class="col-md-6">
            <p><strong>Complementary materials:</strong> {{ $project->complementary_materials }}</p>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <p><strong>Notes:</strong> {{ $project->notes }}</p>
        </div>
    </div>

    <hr/>

    <div class="row">
        <div class="col-md-12">

            <h2>
                Modules
                <small class="pull-right">
                    {!! link_to_route('project.module.create', 'New Module', [$project], ['class' => 'btn btn-success']) !!}
                </small>
            </h2>

            <table class="table table-condensed">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Pages</th>
                    <th>Planned pages</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach($project->rootModules as $module)
                    <tr>
                        <td>{!! link_to_route('project.module.show', $module->name, [$project, $module], ['class' => '']) !!}</td>
                        <td>{{ $module->pages()->count() }}</td>
                        <td>{{ $module->planned_pages }}</td>
                        <td class="shrink">{!! link_to_route('project.module.edit', 'Edit', [$project, $module], ['class' => 'btn btn-xs btn-primary']) !!}</td>
                        <td class="shrink">{!! link_to_route('project.module.submodule.create', 'New Submodule', [$project, $module], ['class' => 'btn btn-xs btn-success']) !!}</td>
                        <td class="shrink">
                            {!! Form::open(['route' => ['project.module.destroy', $project, $module], 'method' => 'delete']) !!}
                                {!! Form::submit('Delete', ['class' => 'btn btn-xs btn-danger']) !!}
                            {!! Form::close() !!}
                        </td>
                    </tr>
                    @foreach($module->submodules as $submodule)
                        @include('project._submodules', ['module' => $submodule, 'count' => 1])
                    @endforeach
                @endforeach
                </tbody>
            </table>

        </div>
    </div>

@endsection