app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('project', 'ProjectController');
Route::resource('project.module', 'ModuleController');
Route::get('project/{project}/module/{module}/submodule/create', [
    'as' => 'project.module.submodule.create', 'uses' => 'ModuleController@submodule'
]);
Route::resource('project.module.page', 'PageController');
Route::resource('project.module.page.image', 'ImageController');
Route::resource('project.module.page.image.proposal', 'ProposalController');

resources/views/partials/breadcrumbs.blade.php
@if(isset($project) && $project->id)

<ol class="breadcrumb">

    @if(isset($project) && $project->id)
        <li>{!! link_to_route('project.show', $project->name, [$project], ['class' => '']) !!}</li>
    @endif

    @if(isset($module))
        <li>{!! link_to_route('project.module.show', $module->name, [$project, $module], ['class' => '']) !!}</li>
    @endif

    @if(isset($page))
        <li>{!! link_to_route('project.module.page.show', $page->sort_order, [$project, $module, $page], ['class' => '']) !!}</li>
    @endif

    @if(isset($image))
        <li>{!! link_to_route('project.module.page.image.show', $image->name, [$project, $module, $page, $image], ['class' => '']) !!}</li>
    @endif

    @if(isset($proposal))
        <li>{!! link_to_route('project.module.page.image.proposal.show', $proposal->name, [$project, $module, $page, $image, $proposal], ['class' => '']) !!}</li>
    @endif

</ol>

@endif

resources/views/partials/nav.blade.php
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">Círculo v2.0</a>
        </div>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav">
                <li><a href="{{ route('project.index') }}">Projects</a></li>
            </ul>

            {{--<ul class="nav navbar-nav navbar-right">--}}
                {{--@if( Auth::guest() )--}}
                    {{--<li><a href="{{ url('/auth/login') }}">Login</a></li>--}}
                    {{--<li><a href="{{ url('/auth/register') }}">Register</a></li>--}}
                {{--@else--}}
                    {{--<li><a href="{{ url('/auth/logout') }}"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Logout</a></li>--}}
                {{--@endif--}}
            {{--</ul>--}}
        </div>
    </div>
</nav>